version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "RestrictedSshAccessStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jkf2mwx84yt6"
s3_prefix = "RestrictedSshAccessStack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "CronJobSchedule=\"cron(30 1 * * ? *)\" PortList=\"22,3306\""

